In [1]:
print("Andrianna Wardill")
print("040167235")

Andrianna Wardill
040167235


## Task 4 Models

In [23]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [6]:
df = pd.read_csv('clean_titanic.csv')
df.sample(3)

,Survived,Pclass,Age,SibSp,Parch,Fare,Sex_male,Embarked_Q,Embarked_S
1,1,1,38.0,1,0,71.2833,False,False,False
136,1,1,19.0,0,2,26.2833,False,False,True
529,0,2,23.0,2,1,11.5000,True,False,True


In [7]:
df.shape

(891, 9)

In [8]:
x = df.drop('Survived', axis=1)
y = df['Survived']

In [9]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [27]:
def model_evaluation(test_size):
    x_train, x_test, y_train, y_test = train_test_split(
        x,
        y, 
        test_size=test_size, 
        random_state=42)
    
    print("TEST model shape: ", x_train.shape, y_train.shape, x_test.shape, y_test.shape)
    print("------------")
    models = {
        "Logistic Regression": LogisticRegression(max_iter=1000),
        "Decision Tree": DecisionTreeClassifier(),
        "Random Forest": RandomForestClassifier()
    }

    results = {}

    for name, model in models.items():
        print(name)
        model.fit(x_train, y_train)

        train_pred = model.predict(x_train)
        # print("TEST train prediciton: ",train_pred)
        test_pred = model.predict(x_test)
        # print("TEST test prediciton: ",test_pred)
        # print("------------")

        train_acc = accuracy_score(y_train, train_pred)
        print("TEST train accuracy: ",train_acc)
        test_acc = accuracy_score(y_test, test_pred)
        print("TEST test accuracy: ",test_acc)

        cm = confusion_matrix(y_test, test_pred)

        print("Confusion Matrix:")
        print(cm)
        print("------------")

        cv_scores = cross_val_score(model, x, y, cv=5)

        print("Cross Validation Score, k=5")
        print(cv_scores)
        print("Average CV")
        print(cv_scores.mean())
        print("------------")
        results[name] = test_acc
    
    return results

In [28]:
print("80/20")
model_evaluation(0.2)

80/20
TEST model shape:  (712, 8) (712,) (179, 8) (179,)
------------
Logistic Regression
TEST train accuracy:  0.800561797752809
TEST test accuracy:  0.8100558659217877
Confusion Matrix:
[[90 15]
 [19 55]]
------------
Cross Validation Score, k=5
[0.7877095  0.78651685 0.78651685 0.76966292 0.8258427 ]
Average CV
0.7912497646098802
------------
Decision Tree
TEST train accuracy:  0.9789325842696629
TEST test accuracy:  0.7821229050279329
Confusion Matrix:
[[85 20]
 [19 55]]
------------
Cross Validation Score, k=5
[0.72625698 0.78089888 0.80337079 0.74719101 0.82022472]
Average CV
0.7755884752997301
------------
Random Forest
TEST train accuracy:  0.9789325842696629
TEST test accuracy:  0.8100558659217877
Confusion Matrix:
[[89 16]
 [18 56]]
------------
Cross Validation Score, k=5
[0.79888268 0.80337079 0.85393258 0.78651685 0.81460674]
Average CV
0.8114619295712762
------------


{'Logistic Regression': 0.8100558659217877,
 'Decision Tree': 0.7821229050279329,
 'Random Forest': 0.8100558659217877}

In [29]:
print("70/30")
model_evaluation(0.3)

70/30
TEST model shape:  (623, 8) (623,) (268, 8) (268,)
------------
Logistic Regression
TEST train accuracy:  0.7993579454253612
TEST test accuracy:  0.8097014925373134
Confusion Matrix:
[[136  21]
 [ 30  81]]
------------
Cross Validation Score, k=5
[0.7877095  0.78651685 0.78651685 0.76966292 0.8258427 ]
Average CV
0.7912497646098802
------------
Decision Tree
TEST train accuracy:  0.9807383627608347
TEST test accuracy:  0.75
Confusion Matrix:
[[122  35]
 [ 32  79]]
------------
Cross Validation Score, k=5
[0.73743017 0.7752809  0.81460674 0.74157303 0.84831461]
Average CV
0.7834410896993284
------------
Random Forest
TEST train accuracy:  0.9807383627608347
TEST test accuracy:  0.7798507462686567
Confusion Matrix:
[[130  27]
 [ 32  79]]
------------
Cross Validation Score, k=5
[0.76536313 0.79775281 0.85955056 0.78089888 0.82022472]
Average CV
0.804758018956751
------------


{'Logistic Regression': 0.8097014925373134,
 'Decision Tree': 0.75,
 'Random Forest': 0.7798507462686567}

In [30]:
print("85:15")
model_evaluation(0.15)

85:15
TEST model shape:  (757, 8) (757,) (134, 8) (134,)
------------
Logistic Regression
TEST train accuracy:  0.8005284015852048
TEST test accuracy:  0.8134328358208955
Confusion Matrix:
[[67 11]
 [14 42]]
------------
Cross Validation Score, k=5
[0.7877095  0.78651685 0.78651685 0.76966292 0.8258427 ]
Average CV
0.7912497646098802
------------
Decision Tree
TEST train accuracy:  0.9775429326287979
TEST test accuracy:  0.7611940298507462
Confusion Matrix:
[[63 15]
 [17 39]]
------------
Cross Validation Score, k=5
[0.72625698 0.78089888 0.80898876 0.74719101 0.83146067]
Average CV
0.7789592618165841
------------
Random Forest
TEST train accuracy:  0.9775429326287979
TEST test accuracy:  0.8283582089552238
Confusion Matrix:
[[68 10]
 [13 43]]
------------
Cross Validation Score, k=5
[0.77094972 0.79213483 0.84831461 0.78089888 0.81460674]
Average CV
0.8013809553700332
------------


{'Logistic Regression': 0.8134328358208955,
 'Decision Tree': 0.7611940298507462,
 'Random Forest': 0.8283582089552238}

## Task 5 Tune Hyperparameters

- n_estimators: number of decision trees in the forest
- max_depth: longest the path from the root to leaf in any tree
- max_features: determines the maximum number of features the algorithms considers when looking for the best split in the nodes

In [48]:
rf_tune = []
def tune_random_forest(n_estimators, max_depth=None, max_features=None):

    model = RandomForestClassifier(
        n_estimators = n_estimators,
        max_depth = max_depth,
        max_features = max_features,
        random_state = 42
    )

    cv_scores = cross_val_score(model, x, y, cv=5)

    print(f"Hyper Parameter Tuning: {n_estimators}, {max_depth}, {max_features}")
    print("Cross Validation Score, k=5")
    print(cv_scores)

    avg_score = cv_scores.mean()
    print("Average CV")
    print(avg_score)
    print("------------")

    rf_tune.append({
        "n_estimators": n_estimators,
        "max_depth": max_depth,
        "max_features": max_features,
        "avg_score": avg_score
    })

In [49]:
tune_random_forest(100)
tune_random_forest(100, 6)
tune_random_forest(100, 6, 'sqrt')
tune_random_forest(200, 6, 'sqrt')
tune_random_forest(100, 6, 'log2')
tune_random_forest(200, 6, 'log2')
tune_random_forest(200)
tune_random_forest(200, 8)
tune_random_forest(200, 8, 'sqrt')
tune_random_forest(100, 8, 'sqrt')
tune_random_forest(200, 8, 'log2')
tune_random_forest(100, 8, 'log2')

Hyper Parameter Tuning: 100, None, None
Cross Validation Score, k=5
[0.7877095  0.81460674 0.85393258 0.78089888 0.84831461]
Average CV
0.8170924612390935
------------
Hyper Parameter Tuning: 100, 6, None
Cross Validation Score, k=5
[0.81564246 0.83146067 0.87078652 0.80898876 0.85393258]
Average CV
0.8361621994852804
------------
Hyper Parameter Tuning: 100, 6, sqrt
Cross Validation Score, k=5
[0.79888268 0.81460674 0.84831461 0.78651685 0.87078652]
Average CV
0.8238214801330738
------------
Hyper Parameter Tuning: 200, 6, sqrt
Cross Validation Score, k=5
[0.77094972 0.80898876 0.84269663 0.78651685 0.87078652]
Average CV
0.8159876969430669
------------
Hyper Parameter Tuning: 100, 6, log2
Cross Validation Score, k=5
[0.79329609 0.80337079 0.84831461 0.79213483 0.84831461]
Average CV
0.8170861841692298
------------
Hyper Parameter Tuning: 200, 6, log2
Cross Validation Score, k=5
[0.79888268 0.81460674 0.84831461 0.79213483 0.84831461]
Average CV
0.8204506936162199
------------
Hyper P

In [50]:
best_tune = max(rf_tune, key=lambda x: x["avg_score"])

print("Best Hyperparameter Combination:")
print(best_tune)

Best Hyperparameter Combination:
{'n_estimators': 100, 'max_depth': 6, 'max_features': None, 'avg_score': np.float64(0.8361621994852804)}


In [51]:
dt_tune = []
def tune_decision_tree(max_depth=None, max_features=None):

    model = DecisionTreeClassifier(
        max_depth = max_depth,
        max_features = max_features,
        random_state = 42
    )

    cv_scores = cross_val_score(model, x, y, cv=5)

    print(f"Hyper Parameter Tuning: {max_depth}, {max_features}")
    print("Cross Validation Score, k=5")
    print(cv_scores)

    avg_score = cv_scores.mean()
    print("Average CV")
    print(avg_score)
    print("------------")

    dt_tune.append({
        "max_depth": max_depth,
        "max_features": max_features,
        "avg_score": avg_score
    })

In [52]:
tune_decision_tree(100)
tune_decision_tree(100, 6)
tune_decision_tree(100, 8)
tune_decision_tree(200)
tune_decision_tree(200, 8)
tune_decision_tree(200, 6)

Hyper Parameter Tuning: 100, None
Cross Validation Score, k=5
[0.74301676 0.78089888 0.79775281 0.74719101 0.83707865]
Average CV
0.7811876216182286
------------
Hyper Parameter Tuning: 100, 6
Cross Validation Score, k=5
[0.79329609 0.76966292 0.83707865 0.78651685 0.80337079]
Average CV
0.7979850605737242
------------
Hyper Parameter Tuning: 100, 8
Cross Validation Score, k=5
[0.74301676 0.78089888 0.79775281 0.74719101 0.83707865]
Average CV
0.7811876216182286
------------
Hyper Parameter Tuning: 200, None
Cross Validation Score, k=5
[0.74301676 0.78089888 0.79775281 0.74719101 0.83707865]
Average CV
0.7811876216182286
------------
Hyper Parameter Tuning: 200, 8
Cross Validation Score, k=5
[0.74301676 0.78089888 0.79775281 0.74719101 0.83707865]
Average CV
0.7811876216182286
------------
Hyper Parameter Tuning: 200, 6
Cross Validation Score, k=5
[0.79329609 0.76966292 0.83707865 0.78651685 0.80337079]
Average CV
0.7979850605737242
------------


In [53]:
best_tune = max(dt_tune, key=lambda x: x["avg_score"])

print("Best Hyperparameter Combination:")
print(best_tune)

Best Hyperparameter Combination:
{'max_depth': 100, 'max_features': 6, 'avg_score': np.float64(0.7979850605737242)}
